<div id="bnr">
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>  
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>  
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>
            <div class="swiper-slide"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/banner.png" style="width: 100%"/></div>  
        </div>
        <div class="swiper-pagination"></div>               
    </div>
</div>