<div id="content">
    <div class="block-head">

        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <center>
            <h1>Không Tìm Thấy Trang Này</h1>
            <img src="<?php echo STATIC_URL ?>/f/v1/images/404-not-found-error.png"/><br/>
            <a href="/">Quay về trang chủ</a>
        </center>   
    </div>
    <div style="clear: both;"></div>

</div><!-- End block-content -->
