<div id="brcmb">
    <a href="#"><span>Đổi mật khẩu</span></a>
</div>
<div id="cont">            
    <div class="us-or">
        <?php if ($this->errors): ?>
            <div class="cr-red" style="border: 1px #3cc051 solid; font-size: 20px">
                <h4 style="text-align: center"> Lỗi!</h4>
                <?php foreach ($this->errors as $error): ?>
                    <p> - <?php echo $error; ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if ($this->success): ?>
            <div class="cr-bl" style="border: 1px #3cc051 solid; font-size: 20px">
                <h4 style="text-align: center"> Thành công !</h4>
                <p> <?php echo $this->success; ?></p>
            </div>
        <?php endif; ?>
        <?php if (!$this->success): ?>
            <div class="form">
                <form method="POST">
                    <table width="100%">
                        <tr>
                            <td  colspan="3">
                                Mật khẩu
                                <input class="input" type="password" name="strPassword" placeholder="Mật khẩu">
                            </td>
                        </tr>

                        <tr>
                            <td  colspan="3">
                                Nhập lại mật khẩu
                                <input class="input" type="password" name="strRePassword" placeholder="Nhập lại mật khẩu">
                            </td>
                        </tr>

                    </table>
                    <div class="button"><button type="submit" class="readmore">Xác nhận</button></div>
                </form>
            </div>
        <?php endif; ?>
    </div>
</div>