<?php
$params= $this->params;
?>
<div id="brcmb">
    <a href="#"><span>Lấy lại mật khẩu</span></a>
</div>
<div id="cont">            
    <div class="us-or">
            <?php if ($this->errors): ?>
            <div class="cr-red" style="border: 1px #3cc051 solid; font-size: 20px">
                <h4 style="text-align: center"> Lỗi!</h4>
                <?php foreach ($this->errors as $error): ?>
                    <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
            </div>
            <?php endif; ?>
            <?php if ($this->success): ?>
            <div class="cr-bl" style="border: 1px #3cc051 solid; font-size: 20px">
                <h4 style="text-align: center"> Thành công !</h4>
                    <p> - <?php echo $this->success; ?></p>
            </div>
            <?php endif; ?>
        <?php if (!$this->success): ?>
        <div class="form">
            <form method="POST">
                <table width="100%">
                    <tr>
                        <td  colspan="3">
                            Email
                            <input class="input" type="text" name="strEmail" placeholder="Nhập địa chỉ Email " value="<?php echo $params['strEmail']; ?>">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="1">
                                <img class="imgCaptcha" src="" >
                                <img title="Lấy mã mới" width="40px" height="30px" onclick="Auth.captcha();" style="cursor: pointer;" src="<?php echo STATIC_URL . '/f/v1/images/refresh2.png' ?>">
                        </td>
                        
                        <td colspan="2">
                            <input class="input" type="text" name="strCaptcha" placeholder="Nhập mã xác nhận">
                        </td>
                    </tr>
                    
                </table>
                <div class="button"><button type="submit" class="readmore">Lấy lại mật khẩu</button></div>
            </form>
        </div>
        <?php endif;?>
    </div>
</div>
<script>
    Auth.index();
    var captchaURL = '<?php echo $this->serverUrl() . $this->Url('captcha', array('controller' => 'captcha', 'action' => 'index')); ?>';
</script>