<?php
$params= $this->params;
use My\General;
$gender = General::getGender();
?>
<div id="brcmb">
    <a href="#"><span>Đăng ký tài khoản</span></a>
</div>
<div id="cont">            
    <div class="us-or">
            <?php if ($this->errors): ?>
            <div class="" style="border: 1px #3cc051 solid; color: #D32929; font-size: 22px">
                <h4 style="text-align: center"> Lỗi!</h4>
                <?php foreach ($this->errors as $error): ?>
                    <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
            </div>
            <?php endif; ?>
        <div class="form">
            <form method="POST">
                <table width="100%">
                    <tr>
                        <td colspan="3" class="note">
                            Họ và tên
                            <input class="input" type="text" name="strFullname" placeholder="Họ và tên" value="<?php echo $params['strFullname']; ?>">
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Tên tài khoản
                            <input class="input" type="text" name="strUsername" placeholder="Tên tài khoản" value="<?php echo $params['strUsername']; ?>">
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Mật khẩu
                            <input class="input" type="password" name="strPassWord" placeholder="Mật khẩu">
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Nhập lại mật khẩu
                            <input class="input" type="password" name="strRePassword" placeholder="Nhập lại mật khẩu">
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Email
                            <input class="input" type="text" name="strEmail" placeholder="Nhập địa chỉ Email " value="<?php echo $params['strEmail']; ?>">
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Số điện thoại
                            <input class="input" type="text" name="strPhone" placeholder="Nhập số điện thoại " value="<?php echo $params['strPhone']; ?>">

                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Ngày sinh
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <select class="input rgYear" name="strYear">
                                <?php
                                $now = getdate();
                                for ($i = ($now["year"] - 5); $i >= ($now["year"] - 105); $i--) :
                                    ?>
                                    <option value="<?php echo $i; ?>" <?php if($params['strYear']== $i ): ?>selected<?php endif; ?>><?php echo $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td width="33.3%">
                            <select class="input rgMoth" name="strMoth">
                                <?php
                                $arrMoth = array('Tháng Một',
                                    'Tháng Hai',
                                    'Tháng Ba',
                                    'Tháng Tư',
                                    'Tháng Năm',
                                    'Tháng Sáu',
                                    'Tháng Bảy',
                                    'Tháng Tám',
                                    'Tháng Chín',
                                    'Tháng Mười',
                                    'Tháng Mười Một',
                                    'Tháng Mười Hai',
                                );
                                for ($i = 1; $i <= 12; $i++) :
                                    ?>
                                    <option value="<?php echo $i; ?>" <?php if ($params['strMoth']==$i): ?>selected<?php endif; ?>><?php echo $arrMoth[$i - 1]; ?> </option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td width="33.3%">                                    
                            <select class="input rgDay" name="strDay">
                                <?php for ($i = 1; $i <= 31; $i++) { ?>
                                    <option value="<?php echo $i; ?>" <?php echo $i; ?> <?php if($params['strDay']==$i): ?>selected<?php endif; ?>><?php echo sprintf("%02d", $i); ?></option>
                            <?php } ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3">
                            Giới Tính
                            <select class="input" name="strGender">
                                <?php foreach ($gender as $keygender => $valgender) : ?>
                                <option value="<?php echo $keygender ?>" <?php if($params['strGender']==$keygender):?> selected <?php endif;?>>  <?php echo $valgender; ?></option>
                            <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    
                    <tr>
                        <td colspan="1">
                                <img class="imgCaptcha" src="" >
                                <img title="Lấy mã mới" width="40px" height="30px" onclick="Auth.captcha();" style="cursor: pointer;" src="<?php echo STATIC_URL . '/f/v1/images/refresh2.png' ?>">
                        </td>
                        
                        <td colspan="2">
                            <input class="input" type="text" name="strCaptcha" placeholder="Nhập mã xác nhận">
                        </td>
                    </tr>
                    
                </table>
                <div class="button"><button type="submit" class="readmore">Đăng ký</button></div>
            </form>
        </div>
    </div>
</div>
<script>
    Auth.index();
    var captchaURL = '<?php echo $this->serverUrl() . $this->Url('captcha', array('controller' => 'captcha', 'action' => 'index')); ?>';
</script>