<div id="content">
    <div class="block-head">

        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <center>
            <h1><?php echo $this->generalDetail['gene_title'];?></h1>
            <div>
                <?php echo $this->generalDetail['gene_content'];?>
            </div>
            <a href="/">Quay về trang chủ</a>
        </center>   
    </div>
    <div style="clear: both;"></div>

</div><!-- End block-content -->
