<div class="u-info">
    <a href="#"><span>Danh sách đơn hàng</span></a>
</div>
<div id="cont">           
    <div class="us-or">
        <?php if(!empty($this->arrOrderList)):
        foreach ($this->arrOrderList as $key => $value):
            ?>
        <div>
            <div class="dtl">
                <p>Mã đơn hàng: <?php echo 'MG'.sprintf("%03d", $value['orde_id']);?></p>
                <p>Ngày: <?php echo date('d/m/Y',$value['orde_created']);?> </p>
                <p>Địa chỉ: <?php echo json_decode($value['orde_detail'],true)['address'];?>  Giá trị đơn hàng: <?php echo number_format($value['orde_total_price'], 0, ",", ".");?> VNĐ </p>
            </div>
            <div class="ls-pd" style="display: none;">
                <ul>
                    <?php
                        foreach($this->arrProductOrder as $k=>$v):
                        if($v['orde_id'] === $value['orde_id']):
                    ?>
                    <li>
                        <div class="f-l img">
                            <img src="<?php echo json_decode($v['prod_image'],true)['thumbImage']['120x120'];?>">
                        </div>
                        <div class="inf">
                            <div class="tt"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $v['prod_slug'], 'productId' => $v['prod_id'])) ?>"><?php echo $v['prod_name'];?></a></div>                               
                            <div class="num">
                                Số lượng: <?php echo $v['prod_quantity'];?>
                            </div>
                            <div class="cr-price"><?php echo number_format($v['prod_price'], 0, ",", ".");?> Vnđ</div>
                        </div>
                        <div class="clear"></div>
                    </li>
                    <?php endif; endforeach;?>
                </ul>
            </div>
        </div>
        <?php endforeach;?>
        <?php if ($this->countPage > 1): 
                    if($this->intPage < $this->countPage):?>
            <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'index','page'=>($this->intPage+1))) ?>"><button class="readmore">Xem Thêm</button><a></div>
                    <?php endif;
                    if($this->intPage > 1):?>
                        <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'index','page'=>($this->intPage-1))) ?>"><button class="back bt-default">Trở Về</button></a></div>
                    <?php endif;?>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>