<div id="brcmb">
    TAGS CONTENT > 
    <a href="<?php echo $this->serverUrl() . $this->Url('tags-content', array('controller' => 'tagscontent', 'action' => 'index', 'tagsSlug' => $this->tagsDetail['tags_cont_slug'], 'tagsID' => $this->tagsDetail['tags_cont_id'])) ?>"><span><?php echo $this->tagsDetail['tags_cont_name']; ?></span></a> >
</div>
<div id="cont">
    <?php if (!empty($this->arrContentList)): ?>
        <div class="ls-pro">               
            <div class="ls">
                <ul>
                    <?php foreach ($this->arrContentList as $key => $value):
                        ?>
                        <li style="overflow:hidden">
                            <div class="f-l img">
                                <img src="<?php echo json_decode($value['cont_image'], true)['thumbImage']['224x224'] ?>"/>
                            </div>
                            <div class="inf">
                                <div  class="tt"><a class="cr-bl"  href="<?php echo $this->serverUrl() . $this->Url('content_detail', array('controller' => 'content', 'action' => 'view', 'contslug' => $value['cont_slug'], 'contId' => $value['cont_id'])) ?>"><?php echo ucfirst($value['cont_title']); ?></a></div>
                                <div ><?php echo $value['cont_summary']; ?></div>
                            </div>
                            <div class="clear"></div>
                        </li>  
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php if ($this->countPage > 1): 
                    if($this->intPage < $this->countPage):?>
            <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('tags-content', array('controller' => 'tagscontent', 'action' => 'index', 'tagsSlug' => $this->tagsDetail['tags_cont_slug'], 'tagsID' => $this->tagsDetail['tags_cont_id'],'page'=>($this->intPage+1))) ?>"><button class="readmore">Xem Thêm</button><a></div>
                    <?php endif;
                    if($this->intPage > 1):?>
                        <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('tags-content', array('controller' => 'tagscontent', 'action' => 'index', 'tagsSlug' => $this->tagsDetail['tags_cont_slug'], 'tagsID' => $this->tagsDetail['tags_cont_id'],'page'=>($this->intPage-1))) ?>"><button class="back bt-default"">Trở Về</button></a></div>
                    <?php endif;?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>