<div id="brcmb">
    <a href="#"><span>STEP ONE</span></a>
</div>
<div id="cont">
    <?php if($this->errors) : ?>
    <div class="error-display text-center">
        <?php
        foreach($this->errors as $errors){
        echo '<span> - '.$errors.'</span><br/>';
        }
        ?>
        <br/>
    </div>
    <?php endif;?>
    <form method="POST" >
        <div class="ls-pro">               
            <div class="step-one">
                <div class="chil">
                    <table>
                        <tr>
                            <td style="width: 15%;text-align: center; padding: 45px 0 0 15px"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/atm.jpg" width="70" height="50"></td>
                            <td style="width: 10%;text-align: center;"><input type="radio"  value="1"  name="payment"></td>
                            <td><b>Thanh toán online qua Thẻ ATM,<br/>
                                    Visa/Master hoặc internet banking</b><br/>
                                Ưu tiên giao hàng trước, không mất thêm phí.<br/>
                                Áp dụng cho tất cả các ngân hàng.
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="chil">
                    <table>
                        <tr>
                            <td style="width: 15%;text-align: center; padding: 45px 0 0 15px"><img src="<?php echo STATIC_URL; ?>/f/mobile/images/ship.PNG" width="70" height="50"></td>
                            <td style="width: 10%;text-align: center;"><input type="radio" value="3" name="payment"></td>
                            <td><b>MegaVita thu tiền tận nơi</b><br/>
                                Trong vòng 1-3 ngày nhân viên của chúng tôi<br/>
                                sẽ đến thu tiền tại địa chỉ của quý khách
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="button"><button class="readmore">Tiếp tục >></button></div>
        </div>
    </form>
</div>