<?php
$arrDetailCategory = $this->arrDetailCategory;
?>
<div id="brcmb">
    <?php foreach ($this->arrCateGradeList as $key => $value) :
        ?>
        <a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value['cate_slug'], 'categoryID' => $value['cate_id'])) ?>">
            <span><?php echo $value['cate_name']; ?></span>
        </a> > 
    <?php endforeach; ?>

</div>
<div id="cont">
    <?php if (!empty($this->arrCategoryList)):
        ?>
        <div class="ls-cat">               
            <div class="ls">
                <ul>
                    <?php
                    foreach ($this->arrCategoryList as $key => $value):
                        if ($value['cate_id'] != $arrDetailCategory['cate_id']):
                            ?>
                            <li><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value['cate_slug'], 'categoryID' => $value['cate_id'])) ?>"><?php echo $value['cate_name']; ?></a></li>
                        <?php endif;
                    endforeach;
                    ?>
                </ul>
            </div>
        </div>
<?php endif; ?>
    <div class="box">
        <div class="tt">
            <h1><?php echo $this->arrDetailCategory['cate_name']; ?></h1>
        </div>
<?php if (!empty($this->arrTopview)): ?>
            <div class="sld">
                <div class="sw-cont">
                    <div class="swiper-wrapper">
                        <?php
                        foreach ($this->arrTopview as $key => $value):
                            ?>
                            <div class="swiper-slide"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><img src="<?php echo json_decode($value['prod_image'], true)['thumbImage']['83x83'] ?>" title="<?php echo $value['prod_name']; ?>" style="width: 100%"/></a></div>
    <?php endforeach; ?>
                    </div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-button-prev"></div>
                </div>
            </div>
    <?php endif; ?>
    </div>
<?php if (!empty($this->arrProductList)): ?>
        <div class="ls-pro">               
            <div class="ls">
                <ul>
    <?php foreach ($this->arrProductList as $key => $value): ?>
                        <li>
                            <div class="f-l img">
                                <img src="<?php echo json_decode($value['prod_image'], true)['thumbImage']['83x83']; ?>"/>
                            </div>
        <?php if ($value['prod_call_price'] == 1): ?>
                                <div class="inf">
                                    <div  class="tt"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><?php echo $value['prod_name']; ?></a></div>
                                    <div class="cr-price">Liên hệ để biết giá</div>
                                </div>
        <?php else: ?>
                                <div class="inf">
                                    <div  class="tt"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value['prod_slug'], 'productId' => $value['prod_id'])) ?>"><?php echo $value['prod_name']; ?></a></div>
                                    <?php if ($value['prod_is_promotion'] == 1): ?><div class="op-price"><?php echo number_format($value['prod_price'], 0, ",", "."); ?> Vnđ</div><?php endif; ?>
                                    <div class="cr-price"><?php echo ($value['prod_is_promotion'] == 1) ? number_format($value['prod_promotion_price'], 0, ",", ".") : number_format($value['prod_price'], 0, ",", "."); ?> Vnđ</div>
                                        <?php if ($value['prod_is_promotion'] == 1): ?>
                                        <div class="percen">
                                            <?php
                                            $percent = 100 - ($value['prod_promotion_price'] * 100 / $value['prod_price']);
                                            echo $percent;
                                            ?>
                                        </div>
                                <?php endif; ?>
                                </div>
        <?php endif; ?>
                            <div class="clear"></div>
                        </li>  
    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <?php if ($this->countPage > 1):
            if ($this->intPage < $this->countPage):
                ?>
                <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $this->arrDetailCategory['cate_slug'], 'categoryID' => $this->arrDetailCategory['cate_id'], 'page' => ($this->intPage + 1))) ?>"><button class="readmore">Xem Thêm</button><a></div>
                        <?php endif;
                        if ($this->intPage > 1):
                            ?>
                            <div class="button"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $this->arrDetailCategory['cate_slug'], 'categoryID' => $this->arrDetailCategory['cate_id'], 'page' => ($this->intPage - 1))) ?>"><button class="back bt-default">Trở Về</button></a></div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
                </div>