<div id="brcmb">
    <a href="#"><span>Thay đổi mật khẩu</span></a>
</div>
<div id="cont">            
    <div class="us-or">
        
        <?php if ($this->errors): ?>
        <div class="alert" style="border: 1px #3cc051 solid; color: #D32929">
            <h4 style="text-align: center"> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        
        <div class="form">
            <form action="" method="POST">
                <table width="100%">                           
                    <tr>
                        <td  colspan="3">
                            Mật khẩu cũ
                            <input value="" type="password" class="input" name="oldPass">
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3">
                            Mật khẩu mới
                            <input value="" type="password" class="input" name="newPass">
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3">
                            Nhập lại mật  khẩu
                            <input value="" type="password" class="input" name="renewPass">
                        </td>
                    </tr>

                </table>
                <div class="button"><button class="readmore" type="submit">Lưu Thay Đổi</button></div>
                <div class="button"><button class="back bt-default" type="button" onClick="history.go(-1);return true;">Trở Về</button></div>
            </form>
        </div>

    </div>
</div>