<?php
use My\General;
$gender = General::getGender();
?>
<div id="brcmb">
    <a href="#"><span>Thông tin tài khoản</span></a>
</div>
<div id="cont">            
    <div class="us-or">
        <?php if ($this->errors): ?>
        <div class="alert" style="border: 1px #3cc051 solid; color: #D32929">
            <h4 style="text-align: center"> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        <div class="form">
            <form method="POST">
                <table width="100%">
                    <tr>
                        <td colspan="3" class="note">
                            Email: <?php echo $this->arrUser['user_email']; ?>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="note">
                            Số điện thoại : <?php echo $this->arrUser['user_phone']; ?>
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3">
                            Tên
                            <input value="<?php echo $this->arrUser['user_fullname']; ?>" type="text" class="input" name="name">
                        </td>
                    </tr>
                    <tr>
                        <td  colspan="3">
                            Ngày sinh
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <select class="input rgYear" name="year">
                                <?php
                                $now = getdate();
                                for ($i = ($now["year"] - 5); $i >= ($now["year"] - 105); $i--) :
                                    ?>
                                <option value="<?php echo $i; ?>" <?php if($i == date('Y',$this->arrUser['user_birthdate'])):?>selected<?php endif;?>><?php echo $i; ?></option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td width="33.3%">
                            <select class="input rgMoth" name="month">
                                <?php
                                    $arrMoth = array('Tháng Một',
                                        'Tháng Hai',
                                        'Tháng Ba',
                                        'Tháng Tư',
                                        'Tháng Năm',
                                        'Tháng Sáu',
                                        'Tháng Bảy',
                                        'Tháng Tám',
                                        'Tháng Chín',
                                        'Tháng Mười',
                                        'Tháng Mười Một',
                                        'Tháng Mười Hai',
                                    );
                                    for ($i = 1; $i <= 12; $i++) :
                                        ?>
                                        <option value="<?php echo $i; ?>" <?php if($i == date('m',$this->arrUser['user_birthdate'])):?>selected<?php endif;?>><?php echo $arrMoth[$i - 1]; ?> </option>
                                <?php endfor; ?>
                            </select>
                        </td>
                        <td width="33.3%">                                    
                            <select class="input rgDay" name="day">
                                <?php for($i=1;$i<=31;$i++){?>
                                    <option value="<?php echo $i;?>" <?php echo $i; ?> <?php if($i == date('d',$this->arrUser['user_birthdate'])):?>selected<?php endif;?>><?php echo sprintf("%02d", $i);?></option>
                                <?php }?>
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <td  colspan="3">
                            Giới Tính
                            <select class="input" name="gender">
                                <?php foreach ($gender as $keygender => $valgender) : ?>
                                <option value="<?php echo $keygender ?>"<?php if($keygender == $this->arrUser['user_gender']):?> selected <?php endif;?>>  <?php echo $valgender; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    
                    <tr>
                        <td  colspan="3">
                            Địa chỉ (Nhập số nhà / tên đường / Xã - Phường)
                            <input value="<?php echo $this->arrUser['user_address']; ?>" type="text" class="input" name="address" placeholder="Nhập Số nhà - tên đường - xã / phường">
                        </td>
                    </tr>
                    
                    <tr>
                        <td width="50%">
                            <select class="input" name="city" id="city">
                                <option <?php if($this->arrUser['city_id']==0):?> selected <?php endif;?>>Tỉnh / Thành Phố</option>
                                    <?php foreach($this->arrCity as $value):?>
                                <option value="<?php echo $value['city_id'];?>" <?php if( (CITY_ID >0) && CITY_ID == $value['city_id'] ):?> selected<?php endif;?>><?php echo $value['city_name'];?></option>
                                    <?php endforeach; ?>
                            </select>
                        </td>
                        <td width="50%">
                            <select class="input" name="district" id="district">
                                    <option>Quận / Huyện</option>
                                    <?php if(!empty($this->arrDistrict)):
                                        foreach($this->arrDistrict as $value):
                                        ?>
                                    <option value="<?php echo $value['dist_id']?>" <?php if( ($this->arrUser['dist_id'] >0) && $this->arrUser['dist_id'] == $value['dist_id'] ):?> selected<?php endif;?> ><?php echo $value['dist_name'];?></option>
                                    <?php endforeach; endif;?>
                            </select>
                        </td>
                    </tr>
                    
                </table>
                <div class="button"><button class="readmore" type="submit">Lưu Thay Đổi</button></div>
                <div class="button"><button class="back bt-default" type="button" onClick="history.go(-1);return true;">Trở Về</button></div>
            </form>
        </div>

    </div>
</div>
<script>
    Profile.index();
</script>